import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'pt' | 'en' | 'fr' | 'es' | 'it' | 'de';
export type Currency = 'BRL' | 'USD' | 'EUR' | 'CAD' | 'MXN' | 'CHF' | 'GBP' | 'AUD' | 'JPY' | 'CNY' | 'INR' | 'KRW' | 'SGD' | 'HKD' | 'NZD' | 'SEK' | 'NOK' | 'DKK' | 'PLN' | 'ZAR' | 'AED' | 'THB' | 'MYR' | 'PHP';

const STORAGE_KEY_LANGUAGE = 'billi-language';
const STORAGE_KEY_CURRENCY = 'billi-currency';

interface User {
  id: string;
  name: string;
  email: string;
  country: string;
  gender: 'M' | 'F' | 'O';
  avatar?: string;
  isPremium: boolean;
  consistencyDays: number;
  maxSaved: number;
  totalBalance: number;
}

interface Group {
  id: string;
  name: string;
  description: string;
  image: string;
  goal: number;
  current: number;
  members: GroupMember[];
  messages: ChatMessage[];
  inviteCode: string;
}

interface GroupMember {
  id: string;
  name: string;
  avatar?: string;
  contribution: number;
  lastContribution: Date;
  rank: number;
}

interface ChatMessage {
  id: string;
  userId: string;
  userName: string;
  content: string;
  timestamp: Date;
  isBot?: boolean;
}

interface Community {
  id: string;
  name: string;
  description: string;
  image: string;
  members: number;
  category: string;
}

interface AppContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  currency: Currency;
  setCurrency: (curr: Currency) => void;
  user: User | null;
  setUser: (user: User | null) => void;
  groups: Group[];
  setGroups: (groups: Group[]) => void;
  communities: Community[];
  formatCurrency: (value: number) => string;
  formatPremiumPrice: (cadValue: number) => string;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  pt: {
    welcome: 'Bem-vindo',
    billionaire: 'Bilionário',
    billionaires: 'Bilionários',
    totalBalance: 'Saldo Total',
    myGroups: 'Meus Grupos',
    createGroup: 'Criar Novo Grupo',
    enterCode: 'Entrar com Código',
    timeline: 'Comunidades',
    profile: 'Perfil',
    home: 'Início',
    group: 'Grupo',
    ranking: 'Ranking',
    chat: 'Chat',
    dreamPanel: 'Painel do Sonho',
    progress: 'Progresso',
    contribute: 'Contribuir',
    join: 'Participar',
    settings: 'Configurações',
    language: 'Idioma',
    currency: 'Moeda',
    theme: 'Tema',
    lightMode: 'Claro',
    darkMode: 'Escuro',
    systemMode: 'Sistema',
    premium: 'Premium',
    consistencyDays: 'Dias de Consistência',
    maxSaved: 'Máximo Economizado',
    shareProgress: 'Compartilhar Progresso',
    scanReceipt: 'Escanear Comprovante',
    aiDetected: 'IA detectou aporte de',
    rankingUpdated: 'Ranking atualizado!',
    partners: 'Parceiros',
    unlockAt: 'Desbloqueia em',
    postAchievement: 'Postar Conquista',
    groupGoal: 'Meta do Grupo',
    yourContribution: 'Sua Contribuição',
    login: 'Entrar',
    signup: 'Cadastrar',
    continueWithGoogle: 'Continuar com Google',
    or: 'ou',
    back: 'Voltar',
    name: 'Nome',
    email: 'E-mail',
    country: 'País',
    gender: 'Sexo',
    male: 'Masculino',
    female: 'Feminino',
    other: 'Outro',
    hideBalance: 'Ocultar saldo',
    showBalance: 'Mostrar saldo',
    justContributed: 'acabou de contribuir',
    // Daily Challenge
    dailyChallenge: 'Desafio Diário',
    save5Today: 'Guarde $5 hoje',
    save10Today: 'Guarde $10 hoje',
    save20Today: 'Guarde $20 hoje',
    makeAnyContribution: 'Faça qualquer contribuição',
    keepStreakAlive: 'Mantenha seu streak',
    challengeComplete: 'Desafio Completo!',
    completeChallenge: 'Completar Desafio',
    save: 'Economize',
    today: 'hoje',
    ofYourGoal: 'da sua meta total',
    standardChallengeDesc: 'Um passo equilibrado rumo aos seus sonhos',
    easyChallengeDesc: 'Pequenos passos levam a grandes conquistas',
    ambitiousChallengeDesc: 'Desafie-se a alcançar mais alto',
    balancedChallengeDesc: 'Consistência é a chave do sucesso',
    doubleChallengeDesc: 'Supere seus limites hoje!',
    microChallengeDesc: 'Cada centavo conta na sua jornada',
    growthChallengeDesc: 'Invista no seu eu futuro',
    // User Stats
    deposits: 'Depósitos',
    bestStreak: 'Melhor Streak',
    progressToLevel: 'Progresso para Nível',
    level: 'Nível',
    billionaireLegend: 'Lenda Bilionária',
    moneyMaster: 'Mestre do Dinheiro',
    savingsPro: 'Pro em Economizar',
    smartSaver: 'Poupador Inteligente',
    risingStar: 'Estrela em Ascensão',
    beginner: 'Iniciante',
    // Quick Win Modal
    keepGoing: 'Continue Assim!',
    dayStreakExclaim: 'dia de streak!',
    daysStreakExclaim: 'dias de streak!',
    // Celebration messages
    youreCrushingIt: 'Você está arrasando! 💪',
    anotherStepToMillions: 'Mais um passo para milhões! 🚀',
    billionaireMoves: 'Movimentos de bilionário! 👑',
    futureThankYou: 'Seu eu futuro agradece! 🙏',
    keepMomentum: 'Mantenha esse ritmo! ⚡',
    // Motivational quotes
    everyDollarSaved: 'Cada real economizado é um real ganho!',
    futureThankYouQuote: 'Seu eu futuro vai te agradecer!',
    smallStepsQuote: 'Pequenos passos levam a grandes conquistas!',
    consistencyQuote: 'Consistência supera intensidade!',
    buildingWealthQuote: 'Você está construindo riqueza, um dia de cada vez!',
    championsQuote: 'Campeões guardam antes de gastar!',
    financialFreedomQuote: 'A liberdade financeira está mais perto do que você imagina!',
    keepStreakQuote: 'Mantenha o streak vivo!',
    moneyPowerQuote: 'Dinheiro guardado é poder acumulado!',
    beABillionaireQuote: 'Seja um bilionário em hábitos!',
    // Join Group Modal
    createGroupToShare: 'Crie um grupo para obter um código de convite!',
    noContributions: 'Sem contribuições há',
    days: 'dias',
    members: 'membros',
    of: 'de',
    reached: 'alcançado',
    inviteFriends: 'Convidar Amigos',
    inviteCode: 'Código de Convite',
    inviteLink: 'Link de Convite',
    shareOn: 'Compartilhar em',
    codeCopied: 'Código copiado!',
    linkCopied: 'Link copiado!',
    shareWithFriends: 'Compartilhe com seus amigos!',
    more: 'Mais',
    enterCodeDescription: 'Digite o código de 6 dígitos do grupo',
    joinGroup: 'Entrar no Grupo',
    joinedGroup: 'Você entrou no grupo!',
    invalidCode: 'Código inválido. Tente novamente.',
    demoCodes: 'Códigos demo',
    shareGroup: 'Compartilhar Grupo',
    notifications: 'Notificações',
    enableNotifications: 'Ativar notificações',
    enableNotificationsDesc: 'Receba alertas quando membros do seu grupo fizerem contribuições.',
    enable: 'Ativar',
    markAllRead: 'Marcar todas como lidas',
    clearAll: 'Limpar todas',
    noNotifications: 'Nenhuma notificação',
    newContribution: 'Nova contribuição!',
    contributedTo: 'contribuiu para',
    continue: 'Continuar',
    installApp: 'Instalar Billi',
    installDescription: 'Adicione o app à sua tela inicial para acesso rápido e offline.',
    installNow: 'Instalar Agora',
    installOnIOS: 'Instalar no iPhone',
    tapShare: 'Toque em Compartilhar',
    tapShareDesc: 'Na barra inferior do Safari',
    addToHomeScreen: 'Adicionar à Tela Inicial',
    addToHomeScreenDesc: 'Role e toque na opção',
    understood: 'Entendi',
    // New translations
    groupPhoto: 'Foto do Grupo',
    addPhotoForGroup: 'Adicione uma foto para o grupo',
    groupName: 'Nome do Grupo',
    groupNamePlaceholder: 'Ex: Viagem para Paris',
    goalAmount: 'Meta',
    description: 'Descrição',
    descriptionOptional: 'Descrição (opcional)',
    descriptionPlaceholder: 'Descreva o objetivo do grupo...',
    createGroupButton: 'Criar Grupo',
    error: 'Erro',
    groupCreated: 'Grupo criado!',
    groupCreatedDesc: 'está pronto para receber contribuições.',
    noGroupsYet: 'Você ainda não tem grupos.',
    createOrJoin: 'Crie um novo grupo ou entre com um código de convite!',
    activeGroups: 'grupos ativos',
    signOut: 'Sair',
    subscribePremium: 'Assinar Premium',
    perMonth: '/mês',
    password: 'Senha',
    forgotPassword: 'Esqueceu a senha?',
    noAccount: 'Não tem conta?',
    hasAccount: 'Já tem conta?',
    signUpNow: 'Cadastre-se',
    signInNow: 'Entre',
    welcomeBack: 'Bem-vindo de volta',
    createAccount: 'Criar conta',
    enterEmail: 'Digite seu e-mail',
    enterPassword: 'Digite sua senha',
    enterName: 'Digite seu nome',
    selectCountry: 'Selecione seu país',
    hello: 'Olá',
    youUser: '(você)',
    noMembersYet: 'Sem membros ainda. Convide seus amigos!',
    welcomeToGroup: 'Bem-vindo ao',
    startContributing: 'Comece a contribuir e convide amigos!',
    quickContribution: 'Contribuição rápida',
    customAmount: 'Valor personalizado',
    enterAmount: 'Digite o valor',
    confirmContribution: 'Confirmar contribuição',
    contributionSuccess: 'Contribuição realizada!',
    addedToGroup: 'adicionados ao grupo',
    streakDay: 'dia de streak',
    streakDays: 'dias de streak',
    phone: 'Telefone',
    city: 'Cidade',
    cityPlaceholder: 'Toronto',
    checkEmail: 'Verifique seu e-mail',
    confirmationSent: 'Enviamos um link de confirmação para verificar sua conta.',
    editGroup: 'Editar Grupo',
    saveChanges: 'Salvar Alterações',
    groupUpdated: 'Grupo atualizado!',
    hideGroup: 'Ocultar grupo',
    leaveGroup: 'Sair do grupo',
    deleteGroup: 'Apagar grupo',
    leaveGroupConfirm: 'Tem certeza que deseja sair deste grupo? Você perderá acesso às contribuições e ao histórico do grupo.',
    deleteGroupConfirm: 'Tem certeza que deseja apagar este grupo? Esta ação é irreversível e todos os dados do grupo serão perdidos permanentemente.',
    cancel: 'Cancelar',
    delete: 'Apagar',
    // Explore Communities
    explore: 'Explorar',
    exploreCommunities: 'Explorar Comunidades',
    exploreDescription: 'Descubra comunidades para compartilhar dicas e experiências',
    searchCommunities: 'Buscar comunidades...',
    shareTipsTitle: 'Compartilhe dicas e experiências',
    shareTipsDescription: 'Entre em comunidades temáticas e troque ideias com pessoas que têm objetivos similares.',
    popularCommunities: 'Comunidades Populares',
    noCommunitiesFound: 'Nenhuma comunidade encontrada',
    tryDifferentSearch: 'Tente uma busca diferente',
    all: 'Todos',
    travel: 'Viagem',
    vehicle: 'Veículo',
    realEstate: 'Imóveis',
    education: 'Educação',
    // Community Chat
    joinedCommunity: 'Entrou na comunidade!',
    welcomeTo: 'Bem-vindo a',
    leftCommunity: 'Saiu da comunidade',
    youLeft: 'Você saiu de',
    member: 'Membro',
    enter: 'Entrar',
    leave: 'Sair',
    posts: 'posts',
    noPostsYet: 'Nenhum post ainda',
    beFirstToPost: 'Seja o primeiro a compartilhar uma dica!',
    shareATip: 'Compartilhe uma dica...',
    justNow: 'Agora',
    // Create Community
    create: 'Criar',
    createCommunity: 'Criar Comunidade',
    communityName: 'Nome da comunidade',
    communityNamePlaceholder: 'Ex: Economizando para Viagens',
    communityDescriptionPlaceholder: 'Descreva o objetivo da comunidade...',
    category: 'Categoria',
    coverImage: 'Imagem de capa',
    uploadImage: 'Enviar imagem',
    changeImage: 'Alterar imagem',
    communityCreated: 'Comunidade criada!',
    isNowAvailable: 'está disponível',
    // New categories
    technology: 'Tecnologia',
    health: 'Saúde',
    investment: 'Investimento',
    emergency: 'Emergência',
    wedding: 'Casamento',
    retirement: 'Aposentadoria',
    family: 'Família',
    hobby: 'Hobby',
    // Scanner
    selectGroup: 'Selecionar Grupo',
    useCamera: 'Usar Câmera',
    uploadFile: 'Enviar Arquivo',
    capture: 'Capturar',
    analyzing: 'Analisando comprovante...',
    detectedAmount: 'Valor Detectado',
    adjustAmount: 'Ajuste o valor se necessário',
    scanAgain: 'Escanear Novamente',
    // Badges
    achievements: 'Conquistas',
    nextBadges: 'Próximas conquistas',
    // Coupons
    unlockByProgress: 'Desbloqueie pelo progresso do grupo',
    couponCode: 'Código do Cupom',
    copyCode: 'Copiar Código',
    visitPartner: 'Visitar Parceiro',
    // Premium
    fullName: 'Nome Completo',
    fullNameRequired: 'Por favor, insira seu nome completo (nome e sobrenome)',
    enterFullName: 'Digite seu nome completo',
    fullNameHint: 'Insira nome e sobrenome',
    freeGroupsRemaining: 'grupos grátis restantes',
    goPremium: 'Seja Premium',
    unlimitedGroups: 'Grupos ilimitados',
    exclusiveBadges: 'Badges exclusivos',
    prioritySupport: 'Suporte prioritário',
    advancedAnalytics: 'Análises avançadas',
    earlyAccess: 'Acesso antecipado a recursos',
    groupLimitReached: 'Você atingiu o limite de 4 grupos!',
    upgradeToPremium: 'Atualize para Premium para grupos ilimitados',
    unlockFullPotential: 'Desbloqueie todo o potencial do Billi',
    cancelAnytime: 'Cancele quando quiser',
    securePayment: 'Pagamento seguro processado pela Stripe',
    month: 'mês',
    // Replies
    replies: 'Respostas',
    writeReply: 'Escreva uma resposta...',
    // New categories
    business: 'Negócios',
    fashion: 'Moda',
    sports: 'Esportes',
    entertainment: 'Entretenimento',
    pets: 'Pets',
    food: 'Comida',
    art: 'Arte',
    music: 'Música',
  },
  en: {
    welcome: 'Welcome',
    billionaire: 'Billionaire',
    billionaires: 'Billionaires',
    totalBalance: 'Total Balance',
    myGroups: 'My Groups',
    createGroup: 'Create New Group',
    enterCode: 'Enter with Code',
    timeline: 'Communities',
    profile: 'Profile',
    home: 'Home',
    group: 'Group',
    ranking: 'Ranking',
    chat: 'Chat',
    dreamPanel: 'Dream Panel',
    progress: 'Progress',
    contribute: 'Contribute',
    join: 'Join',
    settings: 'Settings',
    language: 'Language',
    currency: 'Currency',
    theme: 'Theme',
    lightMode: 'Light',
    darkMode: 'Dark',
    systemMode: 'System',
    premium: 'Premium',
    consistencyDays: 'Consistency Days',
    maxSaved: 'Max Saved',
    shareProgress: 'Share Progress',
    scanReceipt: 'Scan Receipt',
    aiDetected: 'AI detected contribution of',
    rankingUpdated: 'Ranking updated!',
    partners: 'Partners',
    unlockAt: 'Unlocks at',
    postAchievement: 'Post Achievement',
    groupGoal: 'Group Goal',
    yourContribution: 'Your Contribution',
    login: 'Login',
    signup: 'Sign Up',
    continueWithGoogle: 'Continue with Google',
    or: 'or',
    back: 'Back',
    name: 'Name',
    email: 'Email',
    country: 'Country',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    hideBalance: 'Hide balance',
    showBalance: 'Show balance',
    justContributed: 'just contributed',
    // Daily Challenge
    dailyChallenge: 'Daily Challenge',
    save5Today: 'Save $5 today',
    save10Today: 'Save $10 today',
    save20Today: 'Save $20 today',
    makeAnyContribution: 'Make any contribution',
    keepStreakAlive: 'Keep your streak alive',
    challengeComplete: 'Challenge Complete!',
    completeChallenge: 'Complete Challenge',
    save: 'Save',
    today: 'today',
    ofYourGoal: 'of your total goal',
    standardChallengeDesc: 'A balanced step towards your dreams',
    easyChallengeDesc: 'Small steps lead to big achievements',
    ambitiousChallengeDesc: 'Challenge yourself to reach higher',
    balancedChallengeDesc: 'Consistency is the key to success',
    doubleChallengeDesc: 'Push your limits today!',
    microChallengeDesc: 'Every cent counts on your journey',
    growthChallengeDesc: 'Invest in your future self',
    // User Stats
    deposits: 'Deposits',
    bestStreak: 'Best Streak',
    progressToLevel: 'Progress to Level',
    level: 'Level',
    billionaireLegend: 'Billionaire Legend',
    moneyMaster: 'Money Master',
    savingsPro: 'Savings Pro',
    smartSaver: 'Smart Saver',
    risingStar: 'Rising Star',
    beginner: 'Beginner',
    // Quick Win Modal
    keepGoing: 'Keep Going!',
    dayStreakExclaim: 'day streak!',
    daysStreakExclaim: 'days streak!',
    // Celebration messages
    youreCrushingIt: "You're crushing it! 💪",
    anotherStepToMillions: 'Another step to millions! 🚀',
    billionaireMoves: 'Billionaire moves! 👑',
    futureThankYou: 'Your future self says thanks! 🙏',
    keepMomentum: 'Keep that momentum going! ⚡',
    // Motivational quotes
    everyDollarSaved: 'Every dollar saved is a dollar earned!',
    futureThankYouQuote: 'Your future self will thank you!',
    smallStepsQuote: 'Small steps lead to big achievements!',
    consistencyQuote: 'Consistency beats intensity!',
    buildingWealthQuote: "You're building wealth, one day at a time!",
    championsQuote: 'Champions save before they spend!',
    financialFreedomQuote: 'Financial freedom is closer than you think!',
    keepStreakQuote: 'Keep the streak alive!',
    moneyPowerQuote: 'Money saved is power stored!',
    beABillionaireQuote: 'Be a billionaire in habits!',
    // Join Group Modal
    createGroupToShare: 'Create a group to get an invite code to share with friends!',
    noContributions: 'No contributions for',
    days: 'days',
    members: 'members',
    of: 'of',
    reached: 'reached',
    inviteFriends: 'Invite Friends',
    inviteCode: 'Invite Code',
    inviteLink: 'Invite Link',
    shareOn: 'Share on',
    codeCopied: 'Code copied!',
    linkCopied: 'Link copied!',
    shareWithFriends: 'Share with your friends!',
    more: 'More',
    enterCodeDescription: 'Enter the 6-digit group code',
    joinGroup: 'Join Group',
    joinedGroup: 'You joined the group!',
    invalidCode: 'Invalid code. Try again.',
    demoCodes: 'Demo codes',
    shareGroup: 'Share Group',
    notifications: 'Notifications',
    enableNotifications: 'Enable notifications',
    enableNotificationsDesc: 'Get alerts when group members make contributions.',
    enable: 'Enable',
    markAllRead: 'Mark all as read',
    clearAll: 'Clear all',
    noNotifications: 'No notifications',
    newContribution: 'New contribution!',
    contributedTo: 'contributed to',
    continue: 'Continue',
    installApp: 'Install Billi',
    installDescription: 'Add the app to your home screen for quick and offline access.',
    installNow: 'Install Now',
    installOnIOS: 'Install on iPhone',
    tapShare: 'Tap Share',
    tapShareDesc: 'On Safari\'s bottom bar',
    addToHomeScreen: 'Add to Home Screen',
    addToHomeScreenDesc: 'Scroll down and tap the option',
    understood: 'Got it',
    // New translations
    groupPhoto: 'Group Photo',
    addPhotoForGroup: 'Add a photo for your group',
    groupName: 'Group Name',
    groupNamePlaceholder: 'Ex: Trip to Paris',
    goalAmount: 'Goal',
    description: 'Description',
    descriptionOptional: 'Description (optional)',
    descriptionPlaceholder: 'Describe your group\'s goal...',
    createGroupButton: 'Create Group',
    error: 'Error',
    groupCreated: 'Group created!',
    groupCreatedDesc: 'is ready to receive contributions.',
    noGroupsYet: 'You don\'t have any groups yet.',
    createOrJoin: 'Create a new group or join one with an invite code!',
    activeGroups: 'active groups',
    signOut: 'Sign Out',
    subscribePremium: 'Subscribe Premium',
    perMonth: '/month',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    noAccount: 'Don\'t have an account?',
    hasAccount: 'Already have an account?',
    signUpNow: 'Sign up',
    signInNow: 'Sign in',
    welcomeBack: 'Welcome back',
    createAccount: 'Create account',
    enterEmail: 'Enter your email',
    enterPassword: 'Enter your password',
    enterName: 'Enter your name',
    selectCountry: 'Select your country',
    hello: 'Hello',
    youUser: '(you)',
    noMembersYet: 'No members yet. Invite your friends!',
    welcomeToGroup: 'Welcome to',
    startContributing: 'Start contributing and invite your friends!',
    quickContribution: 'Quick contribution',
    customAmount: 'Custom amount',
    enterAmount: 'Enter amount',
    confirmContribution: 'Confirm contribution',
    contributionSuccess: 'Contribution made!',
    addedToGroup: 'added to the group',
    streakDay: 'day streak',
    streakDays: 'days streak',
    phone: 'Phone',
    city: 'City',
    cityPlaceholder: 'Toronto',
    checkEmail: 'Check your email',
    confirmationSent: 'We sent you a confirmation link to verify your account.',
    editGroup: 'Edit Group',
    saveChanges: 'Save Changes',
    groupUpdated: 'Group updated!',
    hideGroup: 'Hide group',
    leaveGroup: 'Leave group',
    deleteGroup: 'Delete group',
    leaveGroupConfirm: 'Are you sure you want to leave this group? You will lose access to contributions and group history.',
    deleteGroupConfirm: 'Are you sure you want to delete this group? This action is irreversible and all group data will be permanently lost.',
    cancel: 'Cancel',
    delete: 'Delete',
    // Explore Communities
    explore: 'Explore',
    exploreCommunities: 'Explore Communities',
    exploreDescription: 'Discover communities to share tips and experiences',
    searchCommunities: 'Search communities...',
    shareTipsTitle: 'Share tips and experiences',
    shareTipsDescription: 'Join thematic communities and exchange ideas with people who have similar goals.',
    popularCommunities: 'Popular Communities',
    noCommunitiesFound: 'No communities found',
    tryDifferentSearch: 'Try a different search',
    all: 'All',
    travel: 'Travel',
    vehicle: 'Vehicle',
    realEstate: 'Real Estate',
    education: 'Education',
    // Community Chat
    joinedCommunity: 'Joined community!',
    welcomeTo: 'Welcome to',
    leftCommunity: 'Left community',
    youLeft: 'You left',
    member: 'Member',
    enter: 'Enter',
    leave: 'Leave',
    posts: 'posts',
    noPostsYet: 'No posts yet',
    beFirstToPost: 'Be the first to share a tip!',
    shareATip: 'Share a tip...',
    justNow: 'Just now',
    // Create Community
    create: 'Create',
    createCommunity: 'Create Community',
    communityName: 'Community name',
    communityNamePlaceholder: 'E.g.: Saving for Travel',
    communityDescriptionPlaceholder: 'Describe the community goal...',
    category: 'Category',
    coverImage: 'Cover image',
    uploadImage: 'Upload image',
    changeImage: 'Change image',
    communityCreated: 'Community created!',
    isNowAvailable: 'is now available',
    // New categories
    technology: 'Technology',
    health: 'Health',
    investment: 'Investment',
    emergency: 'Emergency',
    wedding: 'Wedding',
    retirement: 'Retirement',
    family: 'Family',
    hobby: 'Hobby',
    // Scanner
    selectGroup: 'Select Group',
    useCamera: 'Use Camera',
    uploadFile: 'Upload File',
    capture: 'Capture',
    analyzing: 'Analyzing receipt...',
    detectedAmount: 'Detected Amount',
    adjustAmount: 'Adjust amount if needed',
    scanAgain: 'Scan Again',
    // Badges
    achievements: 'Achievements',
    nextBadges: 'Next badges',
    // Coupons
    unlockByProgress: 'Unlock by group progress',
    couponCode: 'Coupon Code',
    copyCode: 'Copy Code',
    visitPartner: 'Visit Partner',
    // Premium
    fullName: 'Full Name',
    fullNameRequired: 'Please enter your full name (first and last name)',
    enterFullName: 'Enter your full name',
    fullNameHint: 'Please enter first and last name',
    freeGroupsRemaining: 'free groups remaining',
    goPremium: 'Go Premium',
    unlimitedGroups: 'Unlimited groups',
    exclusiveBadges: 'Exclusive badges',
    prioritySupport: 'Priority support',
    advancedAnalytics: 'Advanced analytics',
    earlyAccess: 'Early access to features',
    groupLimitReached: 'You reached the limit of 4 groups!',
    upgradeToPremium: 'Upgrade to Premium for unlimited groups',
    unlockFullPotential: 'Unlock the full potential of Billi',
    cancelAnytime: 'Cancel anytime',
    securePayment: 'Secure payment processed by Stripe',
    month: 'month',
    // Replies
    replies: 'Replies',
    writeReply: 'Write a reply...',
    // New categories
    business: 'Business',
    fashion: 'Fashion',
    sports: 'Sports',
    entertainment: 'Entertainment',
    pets: 'Pets',
    food: 'Food',
    art: 'Art',
    music: 'Music',
  },
  fr: {
    welcome: 'Bienvenue',
    billionaire: 'Milliardaire',
    billionaires: 'Milliardaires',
    totalBalance: 'Solde Total',
    myGroups: 'Mes Groupes',
    createGroup: 'Créer un Groupe',
    enterCode: 'Entrer avec Code',
    timeline: 'Communautés',
    profile: 'Profil',
    home: 'Accueil',
    group: 'Groupe',
    ranking: 'Classement',
    chat: 'Chat',
    dreamPanel: 'Panneau du Rêve',
    progress: 'Progrès',
    contribute: 'Contribuer',
    join: 'Rejoindre',
    settings: 'Paramètres',
    language: 'Langue',
    currency: 'Devise',
    theme: 'Thème',
    lightMode: 'Clair',
    darkMode: 'Sombre',
    systemMode: 'Système',
    premium: 'Premium',
    consistencyDays: 'Jours de Constance',
    maxSaved: 'Max Économisé',
    shareProgress: 'Partager Progrès',
    scanReceipt: 'Scanner Reçu',
    aiDetected: 'IA a détecté une contribution de',
    rankingUpdated: 'Classement mis à jour!',
    partners: 'Partenaires',
    unlockAt: 'Débloque à',
    postAchievement: 'Poster Réussite',
    groupGoal: 'Objectif du Groupe',
    yourContribution: 'Votre Contribution',
    login: 'Connexion',
    signup: 'Inscription',
    continueWithGoogle: 'Continuer avec Google',
    or: 'ou',
    back: 'Retour',
    name: 'Nom',
    email: 'E-mail',
    country: 'Pays',
    gender: 'Sexe',
    male: 'Masculin',
    female: 'Féminin',
    other: 'Autre',
    hideBalance: 'Masquer solde',
    showBalance: 'Afficher solde',
    justContributed: 'vient de contribuer',
    // Daily Challenge
    dailyChallenge: 'Défi Quotidien',
    save5Today: 'Économisez 5$ aujourd\'hui',
    save10Today: 'Économisez 10$ aujourd\'hui',
    save20Today: 'Économisez 20$ aujourd\'hui',
    makeAnyContribution: 'Faites n\'importe quelle contribution',
    keepStreakAlive: 'Maintenez votre série',
    challengeComplete: 'Défi Accompli!',
    completeChallenge: 'Accomplir le Défi',
    // User Stats
    deposits: 'Dépôts',
    bestStreak: 'Meilleure Série',
    progressToLevel: 'Progression vers le Niveau',
    level: 'Niveau',
    billionaireLegend: 'Légende Milliardaire',
    moneyMaster: 'Maître de l\'Argent',
    savingsPro: 'Pro de l\'Épargne',
    smartSaver: 'Épargnant Intelligent',
    risingStar: 'Étoile Montante',
    beginner: 'Débutant',
    // Quick Win Modal
    keepGoing: 'Continuez!',
    dayStreakExclaim: 'jour de série!',
    daysStreakExclaim: 'jours de série!',
    // Celebration messages
    youreCrushingIt: 'Vous êtes au top! 💪',
    anotherStepToMillions: 'Un pas de plus vers les millions! 🚀',
    billionaireMoves: 'Mouvements de milliardaire! 👑',
    futureThankYou: 'Votre futur vous remercie! 🙏',
    keepMomentum: 'Gardez cet élan! ⚡',
    // Motivational quotes
    everyDollarSaved: 'Chaque dollar économisé est un dollar gagné!',
    futureThankYouQuote: 'Votre futur vous remerciera!',
    smallStepsQuote: 'Les petits pas mènent aux grandes réalisations!',
    consistencyQuote: 'La constance bat l\'intensité!',
    buildingWealthQuote: 'Vous construisez votre richesse, jour après jour!',
    championsQuote: 'Les champions économisent avant de dépenser!',
    financialFreedomQuote: 'La liberté financière est plus proche que vous ne pensez!',
    keepStreakQuote: 'Gardez la série vivante!',
    moneyPowerQuote: 'L\'argent économisé est le pouvoir stocké!',
    beABillionaireQuote: 'Soyez milliardaire dans vos habitudes!',
    // Join Group Modal
    createGroupToShare: 'Créez un groupe pour obtenir un code d\'invitation!',
    noContributions: 'Pas de contributions depuis',
    days: 'jours',
    members: 'membres',
    of: 'de',
    reached: 'atteint',
    inviteFriends: 'Inviter des Amis',
    inviteCode: 'Code d\'Invitation',
    inviteLink: 'Lien d\'Invitation',
    shareOn: 'Partager sur',
    codeCopied: 'Code copié!',
    linkCopied: 'Lien copié!',
    shareWithFriends: 'Partagez avec vos amis!',
    more: 'Plus',
    enterCodeDescription: 'Entrez le code à 6 chiffres du groupe',
    joinGroup: 'Rejoindre le Groupe',
    joinedGroup: 'Vous avez rejoint le groupe!',
    invalidCode: 'Code invalide. Réessayez.',
    demoCodes: 'Codes démo',
    shareGroup: 'Partager le Groupe',
    notifications: 'Notifications',
    enableNotifications: 'Activer les notifications',
    enableNotificationsDesc: 'Recevez des alertes lorsque les membres font des contributions.',
    enable: 'Activer',
    markAllRead: 'Tout marquer comme lu',
    clearAll: 'Tout effacer',
    noNotifications: 'Aucune notification',
    newContribution: 'Nouvelle contribution!',
    contributedTo: 'a contribué à',
    continue: 'Continuer',
    installApp: 'Installer Billi',
    installDescription: 'Ajoutez l\'app à votre écran d\'accueil pour un accès rapide et hors ligne.',
    installNow: 'Installer Maintenant',
    installOnIOS: 'Installer sur iPhone',
    tapShare: 'Appuyez sur Partager',
    tapShareDesc: 'Dans la barre inférieure de Safari',
    addToHomeScreen: 'Ajouter à l\'écran d\'accueil',
    addToHomeScreenDesc: 'Faites défiler et appuyez sur l\'option',
    understood: 'Compris',
    // New translations
    groupPhoto: 'Photo du Groupe',
    addPhotoForGroup: 'Ajoutez une photo pour votre groupe',
    groupName: 'Nom du Groupe',
    groupNamePlaceholder: 'Ex: Voyage à Paris',
    goalAmount: 'Objectif',
    description: 'Description',
    descriptionOptional: 'Description (optionnel)',
    descriptionPlaceholder: 'Décrivez l\'objectif du groupe...',
    createGroupButton: 'Créer le Groupe',
    error: 'Erreur',
    groupCreated: 'Groupe créé!',
    groupCreatedDesc: 'est prêt à recevoir des contributions.',
    noGroupsYet: 'Vous n\'avez pas encore de groupes.',
    createOrJoin: 'Créez un nouveau groupe ou rejoignez-en un avec un code d\'invitation!',
    activeGroups: 'groupes actifs',
    signOut: 'Déconnexion',
    subscribePremium: 'Souscrire Premium',
    perMonth: '/mois',
    password: 'Mot de passe',
    forgotPassword: 'Mot de passe oublié?',
    noAccount: 'Pas de compte?',
    hasAccount: 'Déjà un compte?',
    signUpNow: 'Inscrivez-vous',
    signInNow: 'Connectez-vous',
    welcomeBack: 'Bon retour',
    createAccount: 'Créer un compte',
    enterEmail: 'Entrez votre e-mail',
    enterPassword: 'Entrez votre mot de passe',
    enterName: 'Entrez votre nom',
    selectCountry: 'Sélectionnez votre pays',
    hello: 'Bonjour',
    youUser: '(vous)',
    noMembersYet: 'Pas encore de membres. Invitez vos amis!',
    welcomeToGroup: 'Bienvenue dans',
    startContributing: 'Commencez à contribuer et invitez vos amis!',
    quickContribution: 'Contribution rapide',
    customAmount: 'Montant personnalisé',
    enterAmount: 'Entrez le montant',
    confirmContribution: 'Confirmer la contribution',
    contributionSuccess: 'Contribution effectuée!',
    addedToGroup: 'ajoutés au groupe',
    streakDay: 'jour de série',
    streakDays: 'jours de série',
    phone: 'Téléphone',
    city: 'Ville',
    cityPlaceholder: 'Toronto',
    checkEmail: 'Vérifiez votre e-mail',
    confirmationSent: 'Nous vous avons envoyé un lien de confirmation pour vérifier votre compte.',
    editGroup: 'Modifier le Groupe',
    saveChanges: 'Enregistrer',
    groupUpdated: 'Groupe mis à jour!',
    // Explore Communities
    explore: 'Explorer',
    exploreCommunities: 'Explorer les Communautés',
    exploreDescription: 'Découvrez des communautés pour partager conseils et expériences',
    searchCommunities: 'Rechercher des communautés...',
    shareTipsTitle: 'Partagez conseils et expériences',
    shareTipsDescription: 'Rejoignez des communautés thématiques et échangez des idées avec des personnes ayant des objectifs similaires.',
    popularCommunities: 'Communautés Populaires',
    noCommunitiesFound: 'Aucune communauté trouvée',
    tryDifferentSearch: 'Essayez une autre recherche',
    all: 'Tous',
    travel: 'Voyage',
    vehicle: 'Véhicule',
    realEstate: 'Immobilier',
    education: 'Éducation',
    // Community Chat
    joinedCommunity: 'Rejoint la communauté!',
    welcomeTo: 'Bienvenue à',
    leftCommunity: 'Quitté la communauté',
    youLeft: 'Vous avez quitté',
    member: 'Membre',
    enter: 'Entrer',
    leave: 'Quitter',
    posts: 'posts',
    noPostsYet: 'Aucun post encore',
    beFirstToPost: 'Soyez le premier à partager un conseil!',
    shareATip: 'Partagez un conseil...',
    justNow: 'À l\'instant',
    // Create Community
    create: 'Créer',
    createCommunity: 'Créer une Communauté',
    communityName: 'Nom de la communauté',
    communityNamePlaceholder: 'Ex: Économiser pour Voyager',
    communityDescriptionPlaceholder: 'Décrivez l\'objectif de la communauté...',
    category: 'Catégorie',
    coverImage: 'Image de couverture',
    uploadImage: 'Télécharger une image',
    changeImage: 'Changer l\'image',
    communityCreated: 'Communauté créée!',
    isNowAvailable: 'est maintenant disponible',
  },
  es: {
    welcome: 'Bienvenido',
    billionaire: 'Multimillonario',
    billionaires: 'Multimillonarios',
    totalBalance: 'Saldo Total',
    myGroups: 'Mis Grupos',
    createGroup: 'Crear Nuevo Grupo',
    enterCode: 'Entrar con Código',
    timeline: 'Comunidades',
    profile: 'Perfil',
    home: 'Inicio',
    group: 'Grupo',
    ranking: 'Clasificación',
    chat: 'Chat',
    dreamPanel: 'Panel del Sueño',
    progress: 'Progreso',
    contribute: 'Contribuir',
    join: 'Unirse',
    settings: 'Configuración',
    language: 'Idioma',
    currency: 'Moneda',
    theme: 'Tema',
    lightMode: 'Claro',
    darkMode: 'Oscuro',
    systemMode: 'Sistema',
    premium: 'Premium',
    consistencyDays: 'Días de Consistencia',
    maxSaved: 'Máximo Ahorrado',
    shareProgress: 'Compartir Progreso',
    scanReceipt: 'Escanear Recibo',
    aiDetected: 'IA detectó contribución de',
    rankingUpdated: '¡Clasificación actualizada!',
    partners: 'Socios',
    unlockAt: 'Desbloquea en',
    postAchievement: 'Publicar Logro',
    groupGoal: 'Meta del Grupo',
    yourContribution: 'Tu Contribución',
    login: 'Iniciar Sesión',
    signup: 'Registrarse',
    continueWithGoogle: 'Continuar con Google',
    or: 'o',
    back: 'Volver',
    name: 'Nombre',
    email: 'Correo',
    country: 'País',
    gender: 'Género',
    male: 'Masculino',
    female: 'Femenino',
    other: 'Otro',
    hideBalance: 'Ocultar saldo',
    showBalance: 'Mostrar saldo',
    justContributed: 'acaba de contribuir',
    dailyChallenge: 'Desafío Diario',
    save5Today: 'Ahorra $5 hoy',
    save10Today: 'Ahorra $10 hoy',
    save20Today: 'Ahorra $20 hoy',
    makeAnyContribution: 'Haz cualquier contribución',
    keepStreakAlive: 'Mantén tu racha',
    challengeComplete: '¡Desafío Completado!',
    completeChallenge: 'Completar Desafío',
    deposits: 'Depósitos',
    bestStreak: 'Mejor Racha',
    progressToLevel: 'Progreso al Nivel',
    level: 'Nivel',
    billionaireLegend: 'Leyenda Multimillonaria',
    moneyMaster: 'Maestro del Dinero',
    savingsPro: 'Pro del Ahorro',
    smartSaver: 'Ahorrador Inteligente',
    risingStar: 'Estrella en Ascenso',
    beginner: 'Principiante',
    keepGoing: '¡Sigue Así!',
    dayStreakExclaim: '¡día de racha!',
    daysStreakExclaim: '¡días de racha!',
    youreCrushingIt: '¡Lo estás logrando! 💪',
    anotherStepToMillions: '¡Otro paso hacia millones! 🚀',
    billionaireMoves: '¡Movimientos de multimillonario! 👑',
    futureThankYou: '¡Tu yo futuro te lo agradece! 🙏',
    keepMomentum: '¡Mantén ese impulso! ⚡',
    everyDollarSaved: '¡Cada dólar ahorrado es un dólar ganado!',
    futureThankYouQuote: '¡Tu yo futuro te lo agradecerá!',
    smallStepsQuote: '¡Pequeños pasos llevan a grandes logros!',
    consistencyQuote: '¡La consistencia supera la intensidad!',
    buildingWealthQuote: '¡Estás construyendo riqueza, día a día!',
    championsQuote: '¡Los campeones ahorran antes de gastar!',
    financialFreedomQuote: '¡La libertad financiera está más cerca de lo que crees!',
    keepStreakQuote: '¡Mantén la racha viva!',
    moneyPowerQuote: '¡El dinero ahorrado es poder acumulado!',
    beABillionaireQuote: '¡Sé un multimillonario en hábitos!',
    createGroupToShare: '¡Crea un grupo para obtener un código de invitación!',
    noContributions: 'Sin contribuciones desde',
    members: 'miembros',
    of: 'de',
    inviteFriends: 'Invitar Amigos',
    inviteCode: 'Código de Invitación',
    codeCopied: '¡Código copiado!',
    linkCopied: '¡Enlace copiado!',
    shareWithFriends: 'Comparte con tus amigos',
    inviteLink: 'Enlace de Invitación',
    shareOn: 'Compartir en',
    more: 'Más',
    invalidCode: 'Código inválido o grupo no encontrado',
    joinGroup: 'Unirse al Grupo',
    enterCodeDescription: 'Ingresa el código de invitación de 6 dígitos para unirte a un grupo',
    addPhotoForGroup: 'Agrega una foto para tu grupo',
    groupName: 'Nombre del Grupo',
    groupNamePlaceholder: 'Ej: Viaje a Cancún',
    goalAmount: 'Meta',
    description: 'Descripción',
    descriptionOptional: 'Descripción (opcional)',
    descriptionPlaceholder: 'Describe el objetivo del grupo...',
    createGroupButton: 'Crear Grupo',
    error: 'Error',
    groupCreated: '¡Grupo creado!',
    groupCreatedDesc: 'está listo para recibir contribuciones.',
    noGroupsYet: 'Aún no tienes grupos.',
    createOrJoin: '¡Crea un nuevo grupo o únete a uno con un código de invitación!',
    activeGroups: 'grupos activos',
    signOut: 'Cerrar Sesión',
    subscribePremium: 'Suscribirse Premium',
    perMonth: '/mes',
    password: 'Contraseña',
    forgotPassword: '¿Olvidaste tu contraseña?',
    noAccount: '¿No tienes cuenta?',
    hasAccount: '¿Ya tienes cuenta?',
    signUpNow: 'Regístrate',
    signInNow: 'Inicia sesión',
    welcomeBack: 'Bienvenido de vuelta',
    createAccount: 'Crear cuenta',
    enterEmail: 'Ingresa tu correo',
    enterPassword: 'Ingresa tu contraseña',
    enterName: 'Ingresa tu nombre',
    selectCountry: 'Selecciona tu país',
    hello: 'Hola',
    youUser: '(tú)',
    noMembersYet: 'Sin miembros aún. ¡Invita a tus amigos!',
    welcomeToGroup: 'Bienvenido a',
    startContributing: '¡Empieza a contribuir e invita a tus amigos!',
    quickContribution: 'Contribución rápida',
    customAmount: 'Monto personalizado',
    enterAmount: 'Ingresa el monto',
    confirmContribution: 'Confirmar contribución',
    contributionSuccess: '¡Contribución realizada!',
    addedToGroup: 'agregados al grupo',
    streakDay: 'día de racha',
    streakDays: 'días de racha',
    phone: 'Teléfono',
    city: 'Ciudad',
    cityPlaceholder: 'Ciudad de México',
    checkEmail: 'Revisa tu correo',
    confirmationSent: 'Te enviamos un enlace de confirmación para verificar tu cuenta.',
    editGroup: 'Editar Grupo',
    saveChanges: 'Guardar',
    groupUpdated: '¡Grupo actualizado!',
    // Explore Communities
    explore: 'Explorar',
    exploreCommunities: 'Explorar Comunidades',
    exploreDescription: 'Descubre comunidades para compartir consejos y experiencias',
    searchCommunities: 'Buscar comunidades...',
    shareTipsTitle: 'Comparte consejos y experiencias',
    shareTipsDescription: 'Únete a comunidades temáticas e intercambia ideas con personas que tienen objetivos similares.',
    popularCommunities: 'Comunidades Populares',
    noCommunitiesFound: 'No se encontraron comunidades',
    tryDifferentSearch: 'Intenta una búsqueda diferente',
    all: 'Todos',
    travel: 'Viaje',
    vehicle: 'Vehículo',
    realEstate: 'Inmuebles',
    education: 'Educación',
    // Community Chat
    joinedCommunity: '¡Te uniste a la comunidad!',
    welcomeTo: 'Bienvenido a',
    leftCommunity: 'Dejaste la comunidad',
    youLeft: 'Dejaste',
    member: 'Miembro',
    enter: 'Entrar',
    leave: 'Salir',
    posts: 'posts',
    noPostsYet: 'Sin posts todavía',
    beFirstToPost: '¡Sé el primero en compartir un consejo!',
    shareATip: 'Comparte un consejo...',
    justNow: 'Ahora mismo',
    // Create Community
    create: 'Crear',
    createCommunity: 'Crear Comunidad',
    communityName: 'Nombre de la comunidad',
    communityNamePlaceholder: 'Ej: Ahorrando para Viajes',
    communityDescriptionPlaceholder: 'Describe el objetivo de la comunidad...',
    category: 'Categoría',
    coverImage: 'Imagen de portada',
    uploadImage: 'Subir imagen',
    changeImage: 'Cambiar imagen',
    communityCreated: '¡Comunidad creada!',
    isNowAvailable: 'ya está disponible',
  },
  it: {
    welcome: 'Benvenuto',
    billionaire: 'Miliardario',
    billionaires: 'Miliardari',
    totalBalance: 'Saldo Totale',
    myGroups: 'I Miei Gruppi',
    createGroup: 'Crea Nuovo Gruppo',
    enterCode: 'Entra con Codice',
    timeline: 'Comunità',
    profile: 'Profilo',
    home: 'Home',
    group: 'Gruppo',
    ranking: 'Classifica',
    chat: 'Chat',
    dreamPanel: 'Pannello dei Sogni',
    progress: 'Progresso',
    contribute: 'Contribuire',
    join: 'Unisciti',
    settings: 'Impostazioni',
    language: 'Lingua',
    currency: 'Valuta',
    theme: 'Tema',
    lightMode: 'Chiaro',
    darkMode: 'Scuro',
    systemMode: 'Sistema',
    premium: 'Premium',
    consistencyDays: 'Giorni di Costanza',
    maxSaved: 'Massimo Risparmiato',
    shareProgress: 'Condividi Progressi',
    scanReceipt: 'Scansiona Ricevuta',
    aiDetected: 'IA ha rilevato contributo di',
    rankingUpdated: 'Classifica aggiornata!',
    partners: 'Partner',
    unlockAt: 'Sblocca a',
    postAchievement: 'Pubblica Traguardo',
    groupGoal: 'Obiettivo del Gruppo',
    yourContribution: 'Il Tuo Contributo',
    login: 'Accedi',
    signup: 'Registrati',
    continueWithGoogle: 'Continua con Google',
    or: 'o',
    back: 'Indietro',
    name: 'Nome',
    email: 'Email',
    country: 'Paese',
    gender: 'Genere',
    male: 'Maschio',
    female: 'Femmina',
    other: 'Altro',
    hideBalance: 'Nascondi saldo',
    showBalance: 'Mostra saldo',
    justContributed: 'ha appena contribuito',
    dailyChallenge: 'Sfida Giornaliera',
    save5Today: 'Risparmia $5 oggi',
    save10Today: 'Risparmia $10 oggi',
    save20Today: 'Risparmia $20 oggi',
    makeAnyContribution: 'Fai qualsiasi contributo',
    keepStreakAlive: 'Mantieni la serie',
    challengeComplete: 'Sfida Completata!',
    completeChallenge: 'Completa Sfida',
    deposits: 'Depositi',
    bestStreak: 'Miglior Serie',
    progressToLevel: 'Progresso verso Livello',
    level: 'Livello',
    billionaireLegend: 'Leggenda Miliardaria',
    moneyMaster: 'Maestro del Denaro',
    savingsPro: 'Pro del Risparmio',
    smartSaver: 'Risparmiatore Intelligente',
    risingStar: 'Stella Nascente',
    beginner: 'Principiante',
    keepGoing: 'Continua Così!',
    dayStreakExclaim: 'giorno di serie!',
    daysStreakExclaim: 'giorni di serie!',
    youreCrushingIt: 'Stai andando alla grande! 💪',
    anotherStepToMillions: 'Un altro passo verso i milioni! 🚀',
    billionaireMoves: 'Mosse da miliardario! 👑',
    futureThankYou: 'Il tuo futuro ti ringrazia! 🙏',
    keepMomentum: 'Mantieni lo slancio! ⚡',
    everyDollarSaved: 'Ogni dollaro risparmiato è un dollaro guadagnato!',
    futureThankYouQuote: 'Il tuo futuro ti ringrazierà!',
    smallStepsQuote: 'Piccoli passi portano a grandi risultati!',
    consistencyQuote: 'La costanza batte l\'intensità!',
    buildingWealthQuote: 'Stai costruendo ricchezza, giorno dopo giorno!',
    championsQuote: 'I campioni risparmiano prima di spendere!',
    financialFreedomQuote: 'La libertà finanziaria è più vicina di quanto pensi!',
    keepStreakQuote: 'Mantieni viva la serie!',
    moneyPowerQuote: 'Il denaro risparmiato è potere accumulato!',
    beABillionaireQuote: 'Sii un miliardario nelle abitudini!',
    createGroupToShare: 'Crea un gruppo per ottenere un codice invito!',
    noContributions: 'Nessun contributo da',
    members: 'membri',
    of: 'di',
    inviteFriends: 'Invita Amici',
    inviteCode: 'Codice Invito',
    codeCopied: 'Codice copiato!',
    linkCopied: 'Link copiato!',
    shareWithFriends: 'Condividi con i tuoi amici',
    inviteLink: 'Link Invito',
    shareOn: 'Condividi su',
    more: 'Altro',
    invalidCode: 'Codice non valido o gruppo non trovato',
    joinGroup: 'Unisciti al Gruppo',
    enterCodeDescription: 'Inserisci il codice invito a 6 cifre per unirti a un gruppo',
    addPhotoForGroup: 'Aggiungi una foto per il tuo gruppo',
    groupName: 'Nome del Gruppo',
    groupNamePlaceholder: 'Es: Viaggio a Roma',
    goalAmount: 'Obiettivo',
    description: 'Descrizione',
    descriptionOptional: 'Descrizione (opzionale)',
    descriptionPlaceholder: 'Descrivi l\'obiettivo del gruppo...',
    createGroupButton: 'Crea Gruppo',
    error: 'Errore',
    groupCreated: 'Gruppo creato!',
    groupCreatedDesc: 'è pronto a ricevere contributi.',
    noGroupsYet: 'Non hai ancora gruppi.',
    createOrJoin: 'Crea un nuovo gruppo o unisciti a uno con un codice invito!',
    activeGroups: 'gruppi attivi',
    signOut: 'Esci',
    subscribePremium: 'Abbonati Premium',
    perMonth: '/mese',
    password: 'Password',
    forgotPassword: 'Password dimenticata?',
    noAccount: 'Non hai un account?',
    hasAccount: 'Hai già un account?',
    signUpNow: 'Registrati',
    signInNow: 'Accedi',
    welcomeBack: 'Bentornato',
    createAccount: 'Crea account',
    enterEmail: 'Inserisci la tua email',
    enterPassword: 'Inserisci la tua password',
    enterName: 'Inserisci il tuo nome',
    selectCountry: 'Seleziona il tuo paese',
    hello: 'Ciao',
    youUser: '(tu)',
    noMembersYet: 'Nessun membro ancora. Invita i tuoi amici!',
    welcomeToGroup: 'Benvenuto in',
    startContributing: 'Inizia a contribuire e invita i tuoi amici!',
    quickContribution: 'Contributo rapido',
    customAmount: 'Importo personalizzato',
    enterAmount: 'Inserisci l\'importo',
    confirmContribution: 'Conferma contributo',
    contributionSuccess: 'Contributo effettuato!',
    addedToGroup: 'aggiunti al gruppo',
    streakDay: 'giorno di serie',
    streakDays: 'giorni di serie',
    phone: 'Telefono',
    city: 'Città',
    cityPlaceholder: 'Milano',
    checkEmail: 'Controlla la tua email',
    confirmationSent: 'Ti abbiamo inviato un link di conferma per verificare il tuo account.',
    editGroup: 'Modifica Gruppo',
    saveChanges: 'Salva',
    groupUpdated: 'Gruppo aggiornato!',
    // Explore Communities
    explore: 'Esplora',
    exploreCommunities: 'Esplora Comunità',
    exploreDescription: 'Scopri comunità per condividere consigli ed esperienze',
    searchCommunities: 'Cerca comunità...',
    shareTipsTitle: 'Condividi consigli ed esperienze',
    shareTipsDescription: 'Unisciti a comunità tematiche e scambia idee con persone che hanno obiettivi simili.',
    popularCommunities: 'Comunità Popolari',
    noCommunitiesFound: 'Nessuna comunità trovata',
    tryDifferentSearch: 'Prova una ricerca diversa',
    all: 'Tutti',
    travel: 'Viaggio',
    vehicle: 'Veicolo',
    realEstate: 'Immobili',
    education: 'Istruzione',
    // Community Chat
    joinedCommunity: 'Ti sei unito alla comunità!',
    welcomeTo: 'Benvenuto a',
    leftCommunity: 'Hai lasciato la comunità',
    youLeft: 'Hai lasciato',
    member: 'Membro',
    enter: 'Entra',
    leave: 'Esci',
    posts: 'post',
    noPostsYet: 'Nessun post ancora',
    beFirstToPost: 'Sii il primo a condividere un consiglio!',
    shareATip: 'Condividi un consiglio...',
    justNow: 'Adesso',
    // Create Community
    create: 'Crea',
    createCommunity: 'Crea Comunità',
    communityName: 'Nome della comunità',
    communityNamePlaceholder: 'Es: Risparmiare per Viaggi',
    communityDescriptionPlaceholder: 'Descrivi l\'obiettivo della comunità...',
    category: 'Categoria',
    coverImage: 'Immagine di copertina',
    uploadImage: 'Carica immagine',
    changeImage: 'Cambia immagine',
    communityCreated: 'Comunità creata!',
    isNowAvailable: 'è ora disponibile',
  },
  de: {
    welcome: 'Willkommen',
    billionaire: 'Milliardär',
    billionaires: 'Milliardäre',
    totalBalance: 'Gesamtsaldo',
    myGroups: 'Meine Gruppen',
    createGroup: 'Neue Gruppe erstellen',
    enterCode: 'Mit Code beitreten',
    timeline: 'Gemeinschaften',
    profile: 'Profil',
    home: 'Start',
    group: 'Gruppe',
    ranking: 'Rangliste',
    chat: 'Chat',
    dreamPanel: 'Traum-Panel',
    progress: 'Fortschritt',
    contribute: 'Beitragen',
    join: 'Beitreten',
    settings: 'Einstellungen',
    language: 'Sprache',
    currency: 'Währung',
    theme: 'Design',
    lightMode: 'Hell',
    darkMode: 'Dunkel',
    systemMode: 'System',
    premium: 'Premium',
    consistencyDays: 'Tage Beständigkeit',
    maxSaved: 'Max Gespart',
    shareProgress: 'Fortschritt teilen',
    scanReceipt: 'Beleg scannen',
    aiDetected: 'KI erkannte Beitrag von',
    rankingUpdated: 'Rangliste aktualisiert!',
    partners: 'Partner',
    unlockAt: 'Freischalten bei',
    postAchievement: 'Erfolg teilen',
    groupGoal: 'Gruppenziel',
    yourContribution: 'Dein Beitrag',
    login: 'Anmelden',
    signup: 'Registrieren',
    continueWithGoogle: 'Mit Google fortfahren',
    or: 'oder',
    back: 'Zurück',
    name: 'Name',
    email: 'E-Mail',
    country: 'Land',
    gender: 'Geschlecht',
    male: 'Männlich',
    female: 'Weiblich',
    other: 'Andere',
    hideBalance: 'Saldo verbergen',
    showBalance: 'Saldo anzeigen',
    justContributed: 'hat gerade beigetragen',
    dailyChallenge: 'Tägliche Herausforderung',
    save5Today: 'Spare heute $5',
    save10Today: 'Spare heute $10',
    save20Today: 'Spare heute $20',
    makeAnyContribution: 'Mache einen Beitrag',
    keepStreakAlive: 'Halte deine Serie',
    challengeComplete: 'Herausforderung geschafft!',
    completeChallenge: 'Herausforderung abschließen',
    deposits: 'Einzahlungen',
    bestStreak: 'Beste Serie',
    progressToLevel: 'Fortschritt zu Level',
    level: 'Level',
    billionaireLegend: 'Milliardär-Legende',
    moneyMaster: 'Geld-Meister',
    savingsPro: 'Spar-Profi',
    smartSaver: 'Kluger Sparer',
    risingStar: 'Aufsteigender Stern',
    beginner: 'Anfänger',
    keepGoing: 'Weiter so!',
    dayStreakExclaim: 'Tag Serie!',
    daysStreakExclaim: 'Tage Serie!',
    youreCrushingIt: 'Du machst das großartig! 💪',
    anotherStepToMillions: 'Ein weiterer Schritt zu Millionen! 🚀',
    billionaireMoves: 'Milliardär-Bewegungen! 👑',
    futureThankYou: 'Dein zukünftiges Ich dankt dir! 🙏',
    keepMomentum: 'Behalte den Schwung! ⚡',
    everyDollarSaved: 'Jeder gesparte Dollar ist ein verdienter Dollar!',
    futureThankYouQuote: 'Dein zukünftiges Ich wird dir danken!',
    smallStepsQuote: 'Kleine Schritte führen zu großen Erfolgen!',
    consistencyQuote: 'Beständigkeit schlägt Intensität!',
    buildingWealthQuote: 'Du baust Reichtum auf, Tag für Tag!',
    championsQuote: 'Champions sparen, bevor sie ausgeben!',
    financialFreedomQuote: 'Finanzielle Freiheit ist näher als du denkst!',
    keepStreakQuote: 'Halte die Serie am Leben!',
    moneyPowerQuote: 'Gespartes Geld ist gespeicherte Kraft!',
    beABillionaireQuote: 'Sei ein Milliardär in Gewohnheiten!',
    createGroupToShare: 'Erstelle eine Gruppe um einen Einladungscode zu erhalten!',
    noContributions: 'Keine Beiträge seit',
    members: 'Mitglieder',
    of: 'von',
    inviteFriends: 'Freunde einladen',
    inviteCode: 'Einladungscode',
    codeCopied: 'Code kopiert!',
    linkCopied: 'Link kopiert!',
    shareWithFriends: 'Mit Freunden teilen',
    inviteLink: 'Einladungslink',
    shareOn: 'Teilen auf',
    more: 'Mehr',
    invalidCode: 'Ungültiger Code oder Gruppe nicht gefunden',
    joinGroup: 'Gruppe beitreten',
    enterCodeDescription: 'Gib den 6-stelligen Einladungscode ein um einer Gruppe beizutreten',
    addPhotoForGroup: 'Füge ein Foto für deine Gruppe hinzu',
    groupName: 'Gruppenname',
    groupNamePlaceholder: 'Z.B.: Reise nach Berlin',
    goalAmount: 'Ziel',
    description: 'Beschreibung',
    descriptionOptional: 'Beschreibung (optional)',
    descriptionPlaceholder: 'Beschreibe das Gruppenziel...',
    createGroupButton: 'Gruppe erstellen',
    error: 'Fehler',
    groupCreated: 'Gruppe erstellt!',
    groupCreatedDesc: 'ist bereit für Beiträge.',
    noGroupsYet: 'Du hast noch keine Gruppen.',
    createOrJoin: 'Erstelle eine neue Gruppe oder tritt einer mit einem Einladungscode bei!',
    activeGroups: 'aktive Gruppen',
    signOut: 'Abmelden',
    subscribePremium: 'Premium abonnieren',
    perMonth: '/Monat',
    password: 'Passwort',
    forgotPassword: 'Passwort vergessen?',
    noAccount: 'Kein Konto?',
    hasAccount: 'Bereits ein Konto?',
    signUpNow: 'Registrieren',
    signInNow: 'Anmelden',
    welcomeBack: 'Willkommen zurück',
    createAccount: 'Konto erstellen',
    enterEmail: 'E-Mail eingeben',
    enterPassword: 'Passwort eingeben',
    enterName: 'Name eingeben',
    selectCountry: 'Land auswählen',
    hello: 'Hallo',
    youUser: '(du)',
    noMembersYet: 'Noch keine Mitglieder. Lade deine Freunde ein!',
    welcomeToGroup: 'Willkommen bei',
    startContributing: 'Fange an zu sparen und lade deine Freunde ein!',
    quickContribution: 'Schneller Beitrag',
    customAmount: 'Eigener Betrag',
    enterAmount: 'Betrag eingeben',
    confirmContribution: 'Beitrag bestätigen',
    contributionSuccess: 'Beitrag erfolgreich!',
    addedToGroup: 'zur Gruppe hinzugefügt',
    streakDay: 'Tag Serie',
    streakDays: 'Tage Serie',
    phone: 'Telefon',
    city: 'Stadt',
    cityPlaceholder: 'Berlin',
    checkEmail: 'Prüfe deine E-Mail',
    confirmationSent: 'Wir haben dir einen Bestätigungslink gesendet.',
    editGroup: 'Gruppe bearbeiten',
    saveChanges: 'Speichern',
    groupUpdated: 'Gruppe aktualisiert!',
    // Explore Communities
    explore: 'Entdecken',
    exploreCommunities: 'Gemeinschaften entdecken',
    exploreDescription: 'Entdecke Gemeinschaften zum Teilen von Tipps und Erfahrungen',
    searchCommunities: 'Gemeinschaften suchen...',
    shareTipsTitle: 'Tipps und Erfahrungen teilen',
    shareTipsDescription: 'Tritt thematischen Gemeinschaften bei und tausche Ideen mit Menschen aus, die ähnliche Ziele haben.',
    popularCommunities: 'Beliebte Gemeinschaften',
    noCommunitiesFound: 'Keine Gemeinschaften gefunden',
    tryDifferentSearch: 'Versuche eine andere Suche',
    all: 'Alle',
    travel: 'Reise',
    vehicle: 'Fahrzeug',
    realEstate: 'Immobilien',
    education: 'Bildung',
    // Community Chat
    joinedCommunity: 'Der Gemeinschaft beigetreten!',
    welcomeTo: 'Willkommen bei',
    leftCommunity: 'Gemeinschaft verlassen',
    youLeft: 'Du hast verlassen',
    member: 'Mitglied',
    enter: 'Eintreten',
    leave: 'Verlassen',
    posts: 'Beiträge',
    noPostsYet: 'Noch keine Beiträge',
    beFirstToPost: 'Sei der Erste, der einen Tipp teilt!',
    shareATip: 'Teile einen Tipp...',
    justNow: 'Gerade eben',
    // Create Community
    create: 'Erstellen',
    createCommunity: 'Gemeinschaft erstellen',
    communityName: 'Name der Gemeinschaft',
    communityNamePlaceholder: 'Z.B.: Sparen für Reisen',
    communityDescriptionPlaceholder: 'Beschreibe das Ziel der Gemeinschaft...',
    category: 'Kategorie',
    coverImage: 'Titelbild',
    uploadImage: 'Bild hochladen',
    changeImage: 'Bild ändern',
    communityCreated: 'Gemeinschaft erstellt!',
    isNowAvailable: 'ist jetzt verfügbar',
  },
};

// Base currency is CAD - all rates are relative to CAD
const currencyRates: Record<Currency, number> = {
  CAD: 1,
  USD: 0.74,
  EUR: 0.68,
  BRL: 3.70,
  MXN: 12.50,
  CHF: 0.65,
  GBP: 0.58,
  AUD: 1.12,
  JPY: 110.50,
  CNY: 5.35,
  INR: 61.50,
  KRW: 980.00,
  SGD: 1.00,
  HKD: 5.78,
  NZD: 1.22,
  SEK: 7.85,
  NOK: 7.95,
  DKK: 5.08,
  PLN: 2.95,
  ZAR: 13.80,
  AED: 2.72,
  THB: 26.50,
  MYR: 3.45,
  PHP: 41.20,
};

const currencySymbols: Record<Currency, string> = {
  CAD: 'CA$',
  USD: 'US$',
  EUR: '€',
  BRL: 'R$',
  MXN: 'MX$',
  CHF: 'CHF',
  GBP: '£',
  AUD: 'A$',
  JPY: '¥',
  CNY: '¥',
  INR: '₹',
  KRW: '₩',
  SGD: 'S$',
  HKD: 'HK$',
  NZD: 'NZ$',
  SEK: 'kr',
  NOK: 'kr',
  DKK: 'kr',
  PLN: 'zł',
  ZAR: 'R',
  AED: 'د.إ',
  THB: '฿',
  MYR: 'RM',
  PHP: '₱',
};

const currencyDecimals: Record<Currency, number> = {
  CAD: 2, USD: 2, EUR: 2, BRL: 2, MXN: 2, CHF: 2, GBP: 2,
  AUD: 2, NZD: 2, SGD: 2, HKD: 2, ZAR: 2, AED: 2,
  THB: 2, MYR: 2, PHP: 2, PLN: 2, SEK: 2, NOK: 2, DKK: 2,
  INR: 2, CNY: 2, 
  JPY: 0, KRW: 0,
};

const AppContext = createContext<AppContextType | undefined>(undefined);

// Helper to safely get from localStorage
const getStoredValue = <T,>(key: string, defaultValue: T): T => {
  if (typeof window === 'undefined') return defaultValue;
  try {
    const stored = localStorage.getItem(key);
    return stored ? (stored as T) : defaultValue;
  } catch {
    return defaultValue;
  }
};

export const AppProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => 
    getStoredValue<Language>(STORAGE_KEY_LANGUAGE, 'en')
  );
  const [currency, setCurrencyState] = useState<Currency>(() => 
    getStoredValue<Currency>(STORAGE_KEY_CURRENCY, 'CAD')
  );
  const [user, setUser] = useState<User | null>(null);

  // Persist language to localStorage
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem(STORAGE_KEY_LANGUAGE, lang);
    } catch (e) {
      console.error('Failed to save language preference:', e);
    }
  };

  // Persist currency to localStorage
  const setCurrency = (curr: Currency) => {
    setCurrencyState(curr);
    try {
      localStorage.setItem(STORAGE_KEY_CURRENCY, curr);
    } catch (e) {
      console.error('Failed to save currency preference:', e);
    }
  };
  const [groups, setGroups] = useState<Group[]>([
    {
      id: '1',
      name: 'Japan Adventure 🇯🇵',
      description: 'Together to explore the Land of the Rising Sun',
      image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800',
      goal: 12000,
      current: 7800,
      members: [
        { id: '1', name: 'James Wilson', contribution: 2100, lastContribution: new Date(), rank: 1 },
        { id: '2', name: 'Sophie Martin', contribution: 1800, lastContribution: new Date(Date.now() - 86400000), rank: 2 },
        { id: '3', name: 'Michael Chen', contribution: 1650, lastContribution: new Date(Date.now() - 172800000), rank: 3 },
        { id: '4', name: 'Emma Thompson', contribution: 1350, lastContribution: new Date(Date.now() - 604800000 * 2), rank: 4 },
        { id: '5', name: 'Daniel Roy', contribution: 900, lastContribution: new Date(Date.now() - 604800000 * 3), rank: 5 },
      ],
      messages: [
        { id: '1', userId: 'bot', userName: 'Bili Bot', content: 'Billionaire James just contributed $150!', timestamp: new Date(), isBot: true },
        { id: '2', userId: '2', userName: 'Sophie Martin', content: "We're gonna make it! 🚀", timestamp: new Date(Date.now() - 3600000) },
      ],
      inviteCode: 'JAPAN1',
    },
    {
      id: '2',
      name: 'Tesla Dream 🚗',
      description: 'Our sustainable electric vehicle fund',
      image: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800',
      goal: 45000,
      current: 13500,
      members: [
        { id: '1', name: 'Alex Tremblay', contribution: 4500, lastContribution: new Date(), rank: 1 },
        { id: '2', name: 'Jessica Lee', contribution: 3600, lastContribution: new Date(Date.now() - 86400000), rank: 2 },
        { id: '3', name: 'Ryan Côté', contribution: 3000, lastContribution: new Date(Date.now() - 604800000 * 2), rank: 3 },
        { id: '4', name: 'Amanda Singh', contribution: 2400, lastContribution: new Date(Date.now() - 604800000 * 3), rank: 4 },
      ],
      messages: [],
      inviteCode: 'TESLAEV',
    },
  ]);

  const [communities] = useState<Community[]>([
    {
      id: '1',
      name: 'Japan Adventure',
      description: 'Make your dream trip to Japan a reality',
      image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800',
      members: 1247,
      category: 'Travel',
    },
    {
      id: '2',
      name: 'Tesla Dream',
      description: 'Sustainable electric mobility',
      image: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800',
      members: 892,
      category: 'Vehicle',
    },
    {
      id: '3',
      name: 'Downtown Condo',
      description: 'Your apartment in the heart of the city',
      image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800',
      members: 2134,
      category: 'Real Estate',
    },
    {
      id: '4',
      name: 'MBA Toronto',
      description: 'Elite education for your career',
      image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800',
      members: 567,
      category: 'Education',
    },
  ]);

  const getLocale = (): string => {
    const localeMap: Record<Language, string> = {
      pt: 'pt-BR',
      en: 'en-CA',
      fr: 'fr-CA',
      es: 'es-MX',
      it: 'it-IT',
      de: 'de-DE',
    };
    return localeMap[language];
  };

  // Format currency WITHOUT conversion - for all app values (groups, contributions)
  const formatCurrency = (value: number): string => {
    const locale = getLocale();
    const decimals = currencyDecimals[currency];
    return `${currencySymbols[currency]} ${value.toLocaleString(locale, { minimumFractionDigits: decimals, maximumFractionDigits: decimals })}`;
  };

  // Format Premium price WITH conversion from CAD base
  const formatPremiumPrice = (cadValue: number): string => {
    const converted = cadValue * currencyRates[currency];
    const locale = getLocale();
    const decimals = currencyDecimals[currency];
    return `${currencySymbols[currency]} ${converted.toLocaleString(locale, { minimumFractionDigits: decimals, maximumFractionDigits: decimals })}`;
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <AppContext.Provider
      value={{
        language,
        setLanguage,
        currency,
        setCurrency,
        user,
        setUser,
        groups,
        setGroups,
        communities,
        formatCurrency,
        formatPremiumPrice,
        t,
      }}
    >
      {children}
    </AppContext.Provider>
  );
};

export const useApp = () => {
  const context = useContext(AppContext);
  if (context === undefined) {
    throw new Error('useApp must be used within an AppProvider');
  }
  return context;
};
